[package]
name = "sonowire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
log = "0.4.20"
pretty_env_logger = "0.5.0"
sonos = "0.1.4"
sonos_discovery = "0.0.2"
